### PR TITLE
Properly hex-encode stake address in ToJSON DelegationsAndRewards

### LINKED ISSUE #1470: [BUG] - stake address is not correctly displayed under `stake-address-info`
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
stake address is not correctly displayed under `stake-address-info`

**Steps to reproduce**
1. start a local cluster using 1.15.1
2. create a stake address and 1 stake pool and delegate the stake address using a certificate
3. run the below command

```
# CARDANO_NODE_SOCKET_PATH=example/node-bft1/node.sock \
> cardano-cli shelley query stake-address-info \
> --address stake_test1upkzyajamfjnjwa33ndy50awhwxeds7f0tw9t7qmxrfv7jq4s6ft6 \
> --testnet-magic 42
{
    "àl\"v]Úe9;±�ÚJ?®»��ÃÉzÜUø\u001b0ÒÏH": {
        "delegation": "d74b33f303bcec753a4cef91c502d1087419c6fe7abf7e86c1905b35",
        "rewardAccountBalance": 0
    }
}
```

**Expected behavior**
- "àl\"v]Úe9;±�ÚJ?®»��ÃÉzÜUø\u001b0ÒÏH"= the stake address with no unsupported characters

**System info (please complete the following information):**
- OS:  Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)
- Node version
```
# cardano-node --version
cardano-node 1.15.1 - linux-x86_64 - ghc-8.6
git rev 712a287602797e8fd889fbf73e56a08c3d8b004a

# cardano-cli --version
cardano-cli 1.15.1 - linux-x86_64 - ghc-8.6
git rev 712a287602797e8fd889fbf73e56a08c3d8b004a
```

**Screenshots and attachments**
image

### PR DESCRIPTION
**Pull request by intricate**
Closes #1470

### CODE REVIEW

File: cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs [hunk 1]
```diff
@@ -398,7 +399,7 @@ instance ToJSON DelegationsAndRewards where
         -> HashMap Text Aeson.Value
       delegAndRwdToJson acc k (d, r) =
         HMS.insert
-          (Text.decodeLatin1 $ Ledger.serialiseRewardAcnt k)
+          (Text.decodeLatin1 $ B16.encode $ Ledger.serialiseRewardAcnt k)
```
Comment (intricate) [inline cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs:402]: Perhaps I should take this opportunity to encode the stake address as Bech32 here.

Comment (dcoutts) [reply cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs:402]: We can do that as we convert these things over to use the API types rather than the underlying ledger lib types.

**Comment by dcoutts** [comment]
bors merge
