### PR TITLE
RTS workaround converting SIGTERM into SIGINT

### LINKED ISSUE #1697: [BUG] - Node should cleanly exit on SIGTERM
**Internal/Exernal**
*Internal*   if an IOHK staff member.

**Summary**
The node only cleanly exits on SIGINT (ctrl-c) and not SIGTERM. This makes the default systemd signal handler stop the node in a way it takes longer to restart. We work around this by changing the signal it gets in the systemd service, but this should probably be fixed in the node.

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

### PR DESCRIPTION
**Pull request by DavidEichmann**
This is important for graceful shutdown, cleaning up resources in
`bracket` statements.

Fixes #1697

### CODE REVIEW

**Comment by DavidEichmann** [comment]
I should actually throw to the main thread rather than raise SIGINT. That's what the RTS does. I should also upstream this to GHC (see TopHandler).

**Comment by DavidEichmann** [comment]
I'm working on a GHC patch that'll make this the default behavior of the RTS https://gitlab.haskell.org/DavidEichmann/ghc/-/tree/davide/sigterm

File: cardano-node/src/Cardano/Node/Run.hs [hunk 1]
```diff
@@ -105,6 +106,23 @@ runNode
...
+#ifdef UNIX
+    -- Similar implementation to the RTS's handling of SIGINT (see GHC's
+    -- TopHandler.hs)
+    runThreadIdWk <- mkWeakThreadId =<< myThreadId
+    void $ Signals.installHandler
+      Signals.sigTERM
+      (Signals.CatchOnce $ do
+        runThreadIdMay <- deRefWeak runThreadIdWk
+        case runThreadIdMay of
+          Nothing -> return ()
```
Comment (Jimbo4350) [inline cardano-node/src/Cardano/Node/Run.hs:120]: Why not a `putStrLn "thread id no longer exists"` or something to that effect?

File: cardano-node/src/Cardano/Node/Run.hs [hunk 2]
```diff
@@ -105,6 +106,23 @@ runNode
...
+          Just runThreadId -> killThread runThreadId
```
Comment (Jimbo4350) [inline cardano-node/src/Cardano/Node/Run.hs:121]: Should we also put some output here signalling that the thread was successfully killed?

**Review by Jimbo4350 — COMMENTED** [review]
Looks good, a couple comments

File: cardano-node/src/Cardano/Node/Run.hs (hunk 2 above)
Comment (DavidEichmann) [reply cardano-node/src/Cardano/Node/Run.hs:121]: This code was lifted from GHC. We use a weak pointer so that the main thread can be garbage collected. If `doRefWeak` returns `Nothing`, then the main thread must have already exited. I can only imagine that might be possible if the main thread had shut down by some other means and a SIGTERM happened just after that. In that case I'd expect the process to exit gracefully any way, so simply doing nothing here (`return ()`) sounds correct. Is that convincing or do you still think we should output some message?

**Comment by DavidEichmann** [comment]
I've responded to comments by @newhoggy in https://github.com/input-output-hk/cardano-node/pull/3670

File: cardano-node/src/Cardano/Node/Run.hs (hunk 2 above)
Comment (Jimbo4350) [reply cardano-node/src/Cardano/Node/Run.hs]: ^^ Fair points. I think it's fine as is.

**Review by Jimbo4350 — APPROVED** [review]
