### PR TITLE
cardano-cli transaction view: Add friendly certificate printing

### LINKED ISSUE #2386: [BUG] - cardano-node transaction view doesn't format certificates well
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**

*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
Currently, certificates are a huge dump of types. They aren't easy to glance and and know what's in them. Also, some types are displayed very awkwardly, for example metadata hash of pool registration (it should be hex, since that's what all the inputs and outputs expect it to be).

**Steps to reproduce**

**Expected behavior**

**System info (please complete the following information):**
- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Node version

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

### PR DESCRIPTION
**Pull request by cblp**
Fix #2386

### CODE REVIEW

File: cardano-api/src/Cardano/Api/Address.hs [hunk 1]
```diff
@@ -466,6 +466,15 @@ data StakeCredential
        | StakeCredentialByScript  ScriptHash
   deriving (Eq, Ord, Show)
 
+instance ToJSON StakeCredential where
+  toJSON =
+    Aeson.object .
+    \case
+      StakeCredentialByKey keyHash ->
```
Comment (Jimbo4350) [inline cardano-api/src/Cardano/Api/Address.hs:473]: So we use camel case for `ToJSON` instances defined in cardano-api. We should write the keys as `stakingKeyHash` and `stakingScriptHash`. You're also missing an indent in front of `\case`.

File: cardano-api/src/Cardano/Api/Address.hs [hunk 2]
```diff
@@ -606,4 +615,3 @@ fromShelleyStakeReference (Shelley.StakeRefPtr ptr) =
   StakeAddressByPointer (StakeAddressPointer ptr)
 fromShelleyStakeReference Shelley.StakeRefNull =
   NoStakeAddress
```
Comment (Jimbo4350) [inline cardano-api/src/Cardano/Api/Address.hs:617]: I think your editor is automatically removing newlines at the end of the document.

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 3]
```diff
@@ -98,31 +100,35 @@ friendlyWithdrawals :: TxWithdrawals ViewTx era -> Aeson.Value
 friendlyWithdrawals TxWithdrawalsNone = Null
 friendlyWithdrawals (TxWithdrawals _ withdrawals) =
   array
-    [ object
-        [ "address" .= serialiseAddress addr
-        , "network" .= net
-        , "credential" .= cred
-        , "amount" .= friendlyLovelace amount
-        ]
-    | (addr@(StakeAddress net cred), amount, _) <- withdrawals
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:107]: What's wrong with:
```
       ...
      `, "credential" .= friendlyStakeCredential cred
       , "amount" .= friendlyLovelace amount
        ]
    | (addr@(StakeAddress net cred), amount, _) <- withdrawals
    ...
```

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 4]
```diff
@@ -98,31 +100,35 @@ friendlyWithdrawals :: TxWithdrawals ViewTx era -> Aeson.Value
...
 
+friendlyStakeAddress :: StakeAddress -> [(Text, Aeson.Value)]
+friendlyStakeAddress (StakeAddress net cred) =
+  [ "network" .= net
+  , friendlyStakeCredential "" $ fromShelleyStakeCredential cred
+  ]
+
 friendlyTxOut :: TxOut CtxTx era -> Aeson.Value
 friendlyTxOut (TxOut addr amount mdatum) =
+  object $
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:118]: indent in front of case

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 5]
```diff
@@ -131,21 +137,20 @@ friendlyTxOut (TxOut addr amount mdatum) =
...
-      in object $ preAlonzo ++ datum sbe
+      in preAlonzo ++ datum sbe
   where
-   renderDatum :: TxOutDatum CtxTx era -> Aeson.Value
-   renderDatum TxOutDatumNone = Aeson.Null
-   renderDatum (TxOutDatumHash _ h) =
-     Aeson.String $ serialiseToRawBytesHexText h
-   renderDatum (TxOutDatum _ sData) =
-     scriptDataToJson ScriptDataJsonDetailedSchema sData
+    renderDatum :: TxOutDatum CtxTx era -> Aeson.Value
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:142]: > * Indent the `where` keyword with one space to set it
apart from the rest of the code and indent the definitions in a
`where` clause with 1 space.

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 6]
```diff
@@ -131,21 +137,20 @@ friendlyTxOut (TxOut addr amount mdatum) =
...
-
-friendlyStakeReference :: Crypto crypto => Shelley.StakeReference crypto -> Aeson.Value
+friendlyStakeReference :: StakeAddressReference -> (Text, Aeson.Value)
 friendlyStakeReference = \case
-  Shelley.StakeRefBase cred -> toJSON cred
-  Shelley.StakeRefNull -> Null
-  Shelley.StakeRefPtr ptr -> toJSON ptr
+  NoStakeAddress -> "stake reference" .= Null
+  StakeAddressByPointer ptr -> "stake reference" .= String (show ptr)
+  StakeAddressByValue cred -> friendlyStakeCredential "reference" cred
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:153]: What does the `"reference"` mean? All of the keys here should be the same i.e "stake address".

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 7]
```diff
@@ -131,21 +137,20 @@ friendlyTxOut (TxOut addr amount mdatum) =
...
-     scriptDataToJson ScriptDataJsonDetailedSchema sData
+    renderDatum :: TxOutDatum CtxTx era -> Aeson.Value
+    renderDatum TxOutDatumNone = Aeson.Null
+    renderDatum (TxOutDatumHash _ h) =
+      Aeson.String $ serialiseToRawBytesHexText h
+    renderDatum (TxOutDatum _ sData) =
+      scriptDataToJson ScriptDataJsonDetailedSchema sData
 
-
-friendlyStakeReference :: Crypto crypto => Shelley.StakeReference crypto -> Aeson.Value
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:144]: :+1:

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 8]
```diff
@@ -154,8 +159,110 @@ friendlyUpdateProposal = \case
...
+      [ object
+          [ friendlyStakeCredential "" credential
+          , "amount" .= friendlyLovelace lovelace
+          ]
+      | (credential, lovelace) <- addresses
+      ]
+  SendToReservesMIR amount -> "send to reserves" .= friendlyLovelace amount
+  SendToTreasuryMIR amount -> "send to treasury" .= friendlyLovelace amount
+
+friendlyStakeCredential :: Text -> StakeCredential -> (Text, Aeson.Value)
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:210]: I don't understand the point of the "subkey" especially as it's only used once.

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
Right direction but a few comments.

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs (hunk 6 above)
Comment (cblp) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs:153]: To designate this stake address relation to the place where it is used without extra 1-key object.

Comment (cblp) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs]: rewrote

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs (hunk 8 above)
Comment (cblp) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs]: rewrote without it

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs (hunk 4 above)
Comment (cblp) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs:118]: done

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs (hunk 5 above)
Comment (cblp) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs]: I find it unnatural, but done

File: cardano-api/src/Cardano/Api/Address.hs (hunk 1 above)
Comment (cblp) [reply cardano-api/src/Cardano/Api/Address.hs]: done

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs (hunk 3 above)
Comment (cblp) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs:107]: Diving into address is another level of abstraction.

File: cardano-api/src/Cardano/Api/Address.hs (hunk 2 above)
Comment (Jimbo4350) [reply cardano-api/src/Cardano/Api/Address.hs:631]: Yeah it's adding unnecessary diff to the PR, so it would be good if you can turn it off to avoid this.

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs (hunk 3 above)
Comment (Jimbo4350) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs:107]: Yes but you create another separate function that has to go to that level of abstraction anyways. This is less concise.

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 9]
```diff
@@ -154,8 +160,108 @@ friendlyUpdateProposal = \case
 
 friendlyCertificates :: TxCertificates ViewTx era -> Aeson.Value
 friendlyCertificates = \case
-  TxCertificatesNone -> Null
-  TxCertificates _ cs _ -> toJSON $ map textShow cs
+  TxCertificatesNone    -> Null
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:163]: Alignment here

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 10]
```diff
@@ -154,8 +160,108 @@ friendlyUpdateProposal = \case
...
+      "stake pool registration" .= friendlyStakePoolParameters parameters
+    StakePoolRetirementCertificate poolId epochNo ->
+      "stake pool retirement" .= object ["pool" .= poolId, "epoch" .= epochNo]
+
+    -- Special certificates
+    GenesisKeyDelegationCertificate genesisKeyHash delegateKeyHash vrfKeyHash ->
+      "genesis key delegation" .=
+        object
+          [ "genesis key hash"  .= serialiseToRawBytesHexText genesisKeyHash
+          , "delegate key hash" .= serialiseToRawBytesHexText delegateKeyHash
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:192]: Alignment

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
Almost there

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs (hunk 3 above)
Comment (cblp) [reply cardano-cli/src/Cardano/CLI/Run/Friendly.hs:107]: 1. That was wrong explanation. I should rather explain it with a data-structure-driven logic. We have a separate function for each node in the data structure. `friendlyStakeAddress` is the handler for `StakeAddress` type, and is used in several places (2, to be precise).
2. No network information in your version.

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 11]
```diff
@@ -90,62 +92,66 @@ friendlyValidityRange era = \case
...
+            preAlonzo =
+              friendlyPaymentCredential (fromShelleyPaymentCredential cred) :
+              [ "address era" .= Aeson.String "Shelley"
+              , "network" .= net
+              , "address" .= serialiseAddress saddr
               , "amount" .= friendlyTxOutValue amount
+              , "stake reference" .=
+                  friendlyStakeReference (fromShelleyStakeReference stake)
               ]
+            datum :: ShelleyBasedEra era -> [Aeson.Pair]
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:136]: You can use `scriptDataSupportedInEra` instead here

File: cardano-cli/src/Cardano/CLI/Run/Friendly.hs [hunk 12]
```diff
@@ -155,7 +161,107 @@ friendlyUpdateProposal = \case
 friendlyCertificates :: TxCertificates ViewTx era -> Aeson.Value
 friendlyCertificates = \case
   TxCertificatesNone -> Null
-  TxCertificates _ cs _ -> toJSON $ map textShow cs
+  TxCertificates _ cs _ -> array $ map friendlyCertificate cs
+
+friendlyCertificate :: Certificate -> Aeson.Value
+friendlyCertificate =
+  object . (:[]) .
+  \case
```
Comment (Jimbo4350) [inline cardano-cli/src/Cardano/CLI/Run/Friendly.hs:169]: indent missing

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
2 small changes

**Review by Jimbo4350 — APPROVED** [review]

**Comment by cblp** [comment]
bors merge

**Comment by cblp** [comment]
bors merge

**Comment by cblp** [comment]
bors merge
