### PR TITLE
Expect an EpochState from the GetCurrentEpochState query

### LINKED ISSUE #1333: [BUG] - ledger-state dumps cbor
**Internal**

**Summary**
`ledger-state` command returns raw CBOR with an error `Verion mismatch beteen node and consensus, so dumping this as generic CBOR.`

**Steps to reproduce**
`cardano-cli shelley query ledger-state --testnet-magic 42`

**Expected behavior**
dumps json representation of ledger state.

**System info (please complete the following information):**
1.14.0

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #1333.

The `GetCurrentLedgerState` query was changed in consensus to
`GetCurrentEpochState` so that it includes more information that will help
debugging (https://github.com/input-output-hk/ouroboros-network/pull/2288).

In this repo, we were still trying to decode it as a `LedgerState` instead of
an `EpochState`, which always failed. Fix it by trying to decode it as an
`EpochState`.

### CODE REVIEW

File: cardano-api/src/Cardano/Api/LocalStateQuery.hs [hunk 1]
```diff
@@ -208,7 +208,7 @@ queryLocalLedgerState
   => Network
   -> SocketPath
   -> Point blk
-  -> ExceptT LocalStateQueryError IO (Either LByteString (Ledger.LedgerState TPraosStandardCrypto))
+  -> ExceptT LocalStateQueryError IO (Either LByteString (Ledger.EpochState TPraosStandardCrypto))
 queryLocalLedgerState network socketPath point = do
```
Comment (mrBliss) [inline cardano-api/src/Cardano/Api/LocalStateQuery.hs:212]: Do we want to rename `LedgerState` everywhere to `EpochState`, including the CLI command name? I think `LedgerState` is more descriptive than `EpochState`, so I left it as is.

Comment (dcoutts) [reply cardano-api/src/Cardano/Api/LocalStateQuery.hs:212]: > I think LedgerState is more descriptive than EpochState, so I left it as is.

I agree.

**Comment by dcoutts** [comment]
bors merge

**Comment by dcoutts** [comment]
bors merge
